config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get 'home/view'

  get 'parse/:semester', to: 'parse#parse', as: 'parse'
  get 'view/:semester', to: 'home#view', as: 'semester'
  get 'view/:semester/:building', to: 'home#view', as: 'building'
  get 'view/:semester/:building/:room', to: 'home#view', as: 'room'

end

app/models/building.rb
class Building < ActiveRecord::Base
end

app/models/class_room.rb
class ClassRoom < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @semesters = ClassRoom.all.collect{|classroom| classroom.semester}.uniq.sort
    locations = ClassRoom.where("semester=?", params[:semester]).collect{|classroom| classroom.location}
    buildings = []
		@rooms = []
    @buildings = []
    locations.each do |classroom|
			loc=classroom.split(' ')
			buildings << loc[0]
			@rooms << loc[1] if params[:building] == loc[0]
		end
		buildings.sort!.uniq!
    buildings.each do |building|
      name = Building.find_by(code: building)
      if name.nil?
        @buildings << {name: '', code: building}
      else
        @buildings << {name: name.name, code: building}
      end
    end
    p @buildings
		@rooms.sort!.uniq!

    year=Time.now.year.to_s[2..3]
    if (Date.parse("#{Time.now.year.to_s}-1-1")..Date.parse("#{Time.now.year.to_s}-5-15")).cover? Time.now
      @current = "W#{year}"
    elsif (Date.parse("#{Time.now.year.to_s}-8-1")..Date.parse("#{Time.now.year.to_s}-12-20")).cover? Time.now
      @current = "F#{year}"
    else
      @current = 'error'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render 'index' and return if @current == 'error'
    redirect_to semester_path(@current)
  end

  def view
    @classes = []
    ClassRoom.where(semester: params[:semester], location: "#{params[:building]} #{params[:room]}").each do |class_room|
      class_room_info = {}
      class_room_info[:code] = class_room.class_code
      class_room_info[:name] = class_room.class_name
      class_room_info[:instructor] = class_room.instructor
      class_room_info[:start] = class_room.class_start_time
      class_room_info[:end] = class_room.class_end_time
      class_room_info[:days] = []

      next if class_room.class_start_time.empty? or class_room.class_end_time.empty?
      start_time = Time.parse(class_room.class_start_time)
      end_time = Time.parse(class_room.class_end_time)
      class_length = (end_time - start_time)

      if class_room.class_start_time.include? ':00'
        class_room_info[:style] = 'margin-top: 0%; '
      elsif class_room.class_start_time.include? ':10'
        class_room_info[:style] = 'margin-top: 0.8%; '
      elsif class_room.class_start_time.include? ':15'
        class_room_info[:style] = 'margin-top: 1%; '
      elsif class_room.class_start_time.include? ':20'
        class_room_info[:style] = 'margin-top: 1.5%; '
      elsif class_room.class_start_time.include? ':30'
        class_room_info[:style] = 'margin-top: 2%; '
      elsif class_room.class_start_time.include? ':45'
        class_room_info[:style] = 'margin-top: 4%; '
			else
				p "ERROR: unknown time #{class_room.class_start_time}"
      end
      class_room_info[:style] += "height: #{class_length/500}%;"

      days = class_room.day
      if days.include? 'M'
        days.sub!(/M/, '')
        class_room_info[:days] << 'Monday'
      end
      if days.include? 'W'
        days.sub!(/W/, '')
        class_room_info[:days] << 'Wednesday'
      end
      if days.include? 'Th'
        days.sub!(/Th/, '')
        class_room_info[:days] << 'Thursday'
      end
      if days.include? 'F'
        days.sub!(/F/, '')
        class_room_info[:days] << 'Friday'
      end
      if days.include? 'T'
        days.sub!(/T/, '')
        class_room_info[:days] << 'Tuesday'
      end
      @classes << class_room_info
    end

    @days = %w(Monday Tuesday Wednesday Thursday Friday)
  end
end

app/controllers/parse_controller.rb
require 'open-uri'
class ParseController < ApplicationController
  def parse
    excluded_locations = ['Arranged', 'OFF CAMPUS', 'Online']
    page = Nokogiri::HTML(open("https://myaccess.southern.edu/apps/courseschedule/Default.aspx?Term=#{params[:semester]}"))
    num_pages = page.xpath('//div[@id="ctl00_ContentPlaceHolder1_GridView1_ctl01_pagerArea"]//a').count + 1
    (1..num_pages).each do |page_num|
      puts "Parsing page #{page_num}/#{num_pages}: "
      page = Nokogiri::HTML(open("https://myaccess.southern.edu/apps/courseschedule/Default.aspx?Page=#{page_num}&Term=#{params[:semester]}")) if page_num > 1
      data = []
      page.xpath('//table[@id="ctl00_ContentPlaceHolder1_GridView1"]/tr').each do |row|
        info = {}
        column=row.xpath('td')
        next if column.count < 5
        info[:semester] = params[:semester]
        info[:class_code] = column[1].xpath('div[contains(@style, "white-space: nowrap")]').text
        info[:class_name] = column[2].xpath('.//a').text
        info[:instructor] = column.xpath(".//span[substring(@id, string-length(@id) - string-length('Label6') +1) = 'Label6']").text
        info[:location] = column.xpath(".//span[substring(@id, string-length(@id) - string-length('Label11') +1) = 'Label11']").text
        next if excluded_locations.include? info[:location]
        info[:day] = column.xpath(".//span[substring(@id, string-length(@id) - string-length('Label14') +1) = 'Label14']").text
        info[:class_start_time] = column.xpath(".//span[substring(@id, string-length(@id) - string-length('Label15') +1) = 'Label15']").text.gsub(/ /, '')
        info[:class_end_time] = column.xpath(".//span[substring(@id, string-length(@id) - string-length('Label16') +1) = 'Label16']").text.gsub(/ /, '')

        ClassRoom.where(info).first_or_create(info)

      end
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parse_helper.rb
module ParseHelper
end

app/views/home/index.html.erb
Please select a semester above to get started.

app/views/home/view.html.erb
<% if params[:building].nil? %>
    <p xmlns:>Please select a building above</p>
<% elsif params[:room].nil? %>
    <p>Please select a room above</p>
<% else %>

  <table border="1">
    <tr>
      <th>Time</th>
      <% @days.each do |day| %>
        <th><%= day %></th>
      <% end %>
    </tr>
    <% ampm = 'AM' %>
    <% [8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8].each do |hour| %>
      <% ampm = 'PM' if hour == 12 %>
      <tr>
        <td><%= hour %>:00</td>
        <% @days.each do |day| %>
          <td>
						<% i=0 %>
            <% @classes.select{|c| c[:start].starts_with? "#{hour.to_s}:"}.select{|c| c[:start].ends_with? ampm}.select{|c| c[:days].include? day}.each do |item| %>
								<div onClick="javascript:alert('<%= "#{item[:name]}\\n#{item[:start]} - #{item[:end]}\\n#{item[:instructor]}" %>');" class="class_event" style="<%= item[:style] %>"><%= i %><%= "#{item[:code]}" %><br><%= item[:instructor] %></div>
							<% i=i+1 %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>

<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Rooms', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Semester <%= "(#{params[:semester]})" unless params[:semester].nil? %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @semesters.each do |s| %>
              <li><%=  link_to s, semester_path(s) %></li>
            <% end %>
          </ul>
        </li>
        <% unless @buildings.empty? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Building <%= "(#{params[:building]})" unless params[:building].nil? %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @buildings.each do |building| %>
              <% if building[:name].empty? %>
                <% link_name = "#{building[:code]}" %>
              <% else %>
                <% link_name = "#{building[:name]} (#{building[:code]})" %>
              <% end %>
              <li><%= link_to link_name, building_path(semester: params[:semester], building: building[:code]) unless building.nil? %></li>
            <% end %>
          </ul>
        </li>
        <% end %>
				<% unless @rooms.empty? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Room <%= "(#{params[:room]})" unless params[:room].nil? %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @rooms.each do |room| %>
              <li><%= link_to room, room_path(semester: params[:semester], building: params[:building], room: room) %></li>
            <% end %>
          </ul>
        </li>
				<% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="btn-danger"><%= link_to 'Force Refresh', parse_path(params[:semester]), style: 'color: white;' unless params[:semester].nil? %></li>
        <!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rooms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<meta id="viewport" name="viewport" content="width=device-width; initial-scale=1; maximum-scale=1; user-scalable=0;" />
</head>
<body>

<%= render 'layouts/nav' %>

<%= yield %>

</body>
</html>